# Numpy ravel

Return a contiguous flattened array.

A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

In [43]:
import numpy as np
import os

x = np.array([[1, 2, 3], [4, 5, 6]])
print("ravel({}{}{}) = {}".format(os.linesep, x, os.linesep, np.ravel(x)))
print()

print("ravel({}{}{}).T = {}".format(os.linesep, x, os.linesep, np.ravel(x).T))
print()

print("ravel({}{}{}).reshape(-1,1) = {}".format(os.linesep, x, os.linesep, np.ravel(x).reshape(-1,1)))
print()


print("ravel({}{}, order='F'{}) = {}".format(os.linesep, x, os.linesep, np.ravel(x, order='F')))
print()
print("x.T = {}{}".format(os.linesep, x.T))
print()
print("ravel({}{}{}) = {}".format(os.linesep, x.T, os.linesep, np.ravel(x.T)))
print()


ravel(
[[1 2 3]
 [4 5 6]]
) = [1 2 3 4 5 6]

ravel(
[[1 2 3]
 [4 5 6]]
).T = [1 2 3 4 5 6]

ravel(
[[1 2 3]
 [4 5 6]]
).reshape(-1,1) = [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

ravel(
[[1 2 3]
 [4 5 6]], order='F'
) = [1 4 2 5 3 6]

x.T = 
[[1 4]
 [2 5]
 [3 6]]

ravel(
[[1 4]
 [2 5]
 [3 6]]
) = [1 4 2 5 3 6]



# Numpy reshape

Gives a new shape to an array without changing its data.

In [44]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("x = {}".format(x))
print()
print("x.shape = {}".format(x.shape))
print()
print("x.reshape(3,2) = {}".format(x.reshape(3,2)))
print()
print("x.reshape(-1,1) = {}".format(x.reshape(-1,1)))

print()
print("x.reshape(-1,1).shape = {}".format(x.reshape(-1,1).shape))


x = [[1 2 3]
 [4 5 6]]

x.shape = (2, 3)

x.reshape(3,2) = [[1 2]
 [3 4]
 [5 6]]

x.reshape(-1,1) = [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

x.reshape(-1,1).shape = (6, 1)


# Numpy meshgrid

Return coordinate matrices from coordinate vectors.

Make N-D coordinate arrays for vectorized evaluations of N-D scalar/vector fields over N-D grids, given one-dimensional coordinate arrays x1, x2,…, xn.

Changed in version 1.9: 1-D and 0-D cases are allowed.

In [45]:
# for sake of simplicity, consider a 4x3 pixel image
IMAGE_WIDTH = 3
IMAGE_HEIGHT = 4
SCALE = 1.0

mean = np.mean((IMAGE_WIDTH, IMAGE_HEIGHT))

print("IMAGE_WIDTH = {}".format(IMAGE_WIDTH))
print()
print("IMAGE_HEIGHT = {}".format(IMAGE_HEIGHT))
print()
print("mean = {}".format(mean))
print()

x = np.linspace(
    -IMAGE_WIDTH / mean * SCALE,
     IMAGE_WIDTH / mean * SCALE,
     IMAGE_WIDTH)

y = np.linspace(
    -IMAGE_HEIGHT / mean * SCALE,
     IMAGE_HEIGHT / mean * SCALE,
     IMAGE_HEIGHT)

print("x = {}".format(x))
print()
print("y = {}".format(y))
print()

X, Y = np.meshgrid(x, y)

print("X, Y = np.meshgrid(x, y)")
print()
print("X = {}{}".format(os.linesep, X))
print()
print("Y = {}{}".format(os.linesep, Y))
print()

x = np.ravel(X)
y = np.ravel(Y)

print("x = np.ravel(X)")
print()
print("y = np.ravel(Y)")
print()

print("x = {}".format(x))
print()
print("y = {}".format(y))
print()

x = np.ravel(X).reshape(-1, 1)
y = np.ravel(Y).reshape(-1, 1)

print("x = np.ravel(X).reshape(-1, 1)")
print("y = np.ravel(Y).reshape(-1, 1)")

print("x = {}".format(x))
print()
print("y = {}".format(y))
print()

array_from_x_y = np.array((x,y))

print("array_from_x_y = np.array((x,y)")
print()
print("array_from_x_y = {}".format(array_from_x_y))
print()

concat_array_from_x_y = np.concatenate(np.array((x,y)), axis=1)

print("concat_array_from_x_y = np.concatenate(np.array((x,y)), axis=1)")
print()
print("concat_array_from_x_y = {}".format(concat_array_from_x_y))
print()



IMAGE_WIDTH = 3

IMAGE_HEIGHT = 4

mean = 3.5

x = [-0.85714286  0.          0.85714286]

y = [-1.14285714 -0.38095238  0.38095238  1.14285714]

X, Y = np.meshgrid(x, y)

X = 
[[-0.85714286  0.          0.85714286]
 [-0.85714286  0.          0.85714286]
 [-0.85714286  0.          0.85714286]
 [-0.85714286  0.          0.85714286]]

Y = 
[[-1.14285714 -1.14285714 -1.14285714]
 [-0.38095238 -0.38095238 -0.38095238]
 [ 0.38095238  0.38095238  0.38095238]
 [ 1.14285714  1.14285714  1.14285714]]

x = np.ravel(X)

y = np.ravel(Y)

x = [-0.85714286  0.          0.85714286 -0.85714286  0.          0.85714286
 -0.85714286  0.          0.85714286 -0.85714286  0.          0.85714286]

y = [-1.14285714 -1.14285714 -1.14285714 -0.38095238 -0.38095238 -0.38095238
  0.38095238  0.38095238  0.38095238  1.14285714  1.14285714  1.14285714]

x = np.ravel(X).reshape(-1, 1)
y = np.ravel(Y).reshape(-1, 1)
x = [[-0.85714286]
 [ 0.        ]
 [ 0.85714286]
 [-0.85714286]
 [ 0.        ]
 [ 0.85714286]
 [-0.8571